# Exercise - Pricing Swaptions

#### Notation Commands

$$\newcommand{\Black}{\mathcal{B}}
\newcommand{\Blackcall}{\Black_{\mathrm{call}}}
\newcommand{\Blackput}{\Black_{\mathrm{put}}}
\newcommand{\EcondS}{\hat{S}_{\mathrm{conditional}}}
\newcommand{\Efwd}{\mathbb{E}^{T}}
\newcommand{\Ern}{\mathbb{E}^{\mathbb{Q}}}
\newcommand{\Tfwd}{T_{\mathrm{fwd}}}
\newcommand{\Tunder}{T_{\mathrm{bond}}}
\newcommand{\accint}{A}
\newcommand{\carry}{\widetilde{\cpn}}
\newcommand{\cashflow}{C}
\newcommand{\convert}{\phi}
\newcommand{\cpn}{c}
\newcommand{\ctd}{\mathrm{CTD}}
\newcommand{\disc}{Z}
\newcommand{\done}{d_{1}}
\newcommand{\dt}{\Delta t}
\newcommand{\dtwo}{d_{2}}
\newcommand{\flatvol}{\sigma_{\mathrm{flat}}}
\newcommand{\flatvolT}{\sigma_{\mathrm{flat},T}}
\newcommand{\float}{\mathrm{flt}}
\newcommand{\freq}{m}
\newcommand{\futprice}{\mathcal{F}(t,T)}
\newcommand{\futpriceDT}{\mathcal{F}(t+h,T)}
\newcommand{\futpriceT}{\mathcal{F}(T,T)}
\newcommand{\futrate}{\mathscr{f}}
\newcommand{\fwdprice}{F(t,T)}
\newcommand{\fwdpriceDT}{F(t+h,T)}
\newcommand{\fwdpriceT}{F(T,T)}
\newcommand{\fwdrate}{f}
\newcommand{\fwdvol}{\sigma_{\mathrm{fwd}}}
\newcommand{\fwdvolTi}{\sigma_{\mathrm{fwd},T_i}}
\newcommand{\grossbasis}{B}
\newcommand{\hedge}{\Delta}
\newcommand{\ivol}{\sigma_{\mathrm{imp}}}
\newcommand{\logprice}{p}
\newcommand{\logyield}{y}
\newcommand{\mat}{(n)}
\newcommand{\nargcond}{d_{1}}
\newcommand{\nargexer}{d_{2}}
\newcommand{\netbasis}{\tilde{\grossbasis}}
\newcommand{\normcdf}{\mathcal{N}}
\newcommand{\notional}{K}
\newcommand{\pfwd}{P_{\mathrm{fwd}}}
\newcommand{\pnl}{\Pi}
\newcommand{\price}{P}
\newcommand{\probexer}{\hat{\mathcal{P}}_{\mathrm{exercise}}}
\newcommand{\pvstrike}{K^*}
\newcommand{\refrate}{r^{\mathrm{ref}}}
\newcommand{\rrepo}{r^{\mathrm{repo}}}
\newcommand{\spotrate}{r}
\newcommand{\spread}{s}
\newcommand{\strike}{K}
\newcommand{\swap}{\mathrm{sw}}
\newcommand{\swaprate}{\cpn_{\swap}}
\newcommand{\tbond}{\mathrm{fix}}
\newcommand{\ttm}{\tau}
\newcommand{\value}{V}
\newcommand{\vega}{\nu}
\newcommand{\years}{\tau}
\newcommand{\yearsACT}{\tau_{\mathrm{act/360}}}
\newcommand{\yield}{Y}$$

In [1]:
import pandas as pd

# 1. Pricing the Swaption

## Swaption Vol Data

The file `data/swaption_vol_data_2025-06-30.xlsx` has market data on the implied volatility skews for swaptions. Note that it has several columns:
* `expry`: expiration of the swaption
* `tenor`: tenor of the underlying swap
* `model`: the model by which the volatility is quoted. (All are Black.)
* `-200`, `-100`, etc.: The strike listed as difference from ATM strike (bps). Note that ATM is considered to be the **forward swapa rate** which you can calculate.

Your data: you will use a single row of this data for the `1x4` swaption.
* date: `2025-06-30`
* expiration: 1yr
* tenor: 4yrs

In [3]:
SWAPTION_DATA_FILE = "./data/swaption_vol_data_2025-06-30.xlsx"

swaption = pd.read_excel(SWAPTION_DATA_FILE)

swaption

,reference,instrument,model,date,expiration,tenor,-200,-100,-50,-25,0,25,50,100,200
0,SOFR,swaption,black,2025-06-30,1,1,72.250,46.870,39.100,36.000,33.39,31.300,29.760,28.17,28.660
1,SOFR,swaption,black,2025-06-30,1,2,65.780,44.400,37.970,35.460,33.39,31.750,30.530,29.19,29.300
2,SOFR,swaption,black,2025-06-30,1,3,57.870,40.610,35.560,33.650,32.11,30.920,30.060,29.14,29.290
3,SOFR,swaption,black,2025-06-30,1,4,54.405,38.565,33.925,32.195,30.83,29.805,29.095,28.43,28.885
4,SOFR,swaption,black,2025-06-30,1,5,50.940,36.520,32.290,30.740,29.55,28.690,28.130,27.72,28.480

## Rate Data

The file `data/cap_curves_2025-06-30.xlsx` gives 
* SOFR swap rates, 
* their associated discount factors
* their associated forward interest rates.

You will not need the cap data (flat or forward vols) for this problem.

In [4]:
RATE_DATA_FILE = "./data/cap_curves_2025-06-30.xlsx"

rate = pd.read_excel(RATE_DATA_FILE)

rate

    tenor  swap rates  spot rates  discounts  forwards  flat vols  fwd vols
0    0.25    0.042353    0.042353   0.989523       NaN        NaN       NaN
1    0.50    0.040859    0.040852   0.979883  0.039351   0.156842  0.156842
2    0.75    0.039391    0.039372   0.971043  0.036414   0.180709  0.201708
3    1.00    0.038115    0.038083   0.962807  0.034217   0.204576  0.240464
4    1.25    0.036704    0.036653   0.955417  0.030938   0.242127  0.328341
5    1.50    0.035655    0.035590   0.948239  0.030280   0.268642  0.336521
6    1.75    0.034942    0.034868   0.941054  0.030542   0.285885  0.336809
7    2.00    0.034453    0.034374   0.933835  0.030919   0.295615  0.328654
8    2.25    0.034000    0.033916   0.926827  0.030248   0.299596  0.312413
9    2.50    0.033750    0.033665   0.919605  0.031414   0.299589  0.296022
10   2.75    0.033619    0.033536   0.912252  0.032242   0.297355  0.282155
11   3.00    0.033568    0.033490   0.904790  0.032987   0.294658  0.276057
12   3.25    0.033513    0.033438   0.897427  0.032816   0.292854  0.278780
13   3.50    0.033458    0.033386   0.890150  0.032700   0.291688  0.281472
14   3.75    0.033499    0.033434   0.882623  0.034113   0.290499  0.280533
15   4.00    0.033542    0.033484   0.875134  0.034231   0.288628  0.271292
16   4.25    0.033585    0.033533   0.867689  0.034320   0.285622  0.255268
17   4.50    0.033628    0.033582   0.860288  0.034412   0.281863  0.241018
18   4.75    0.033739    0.033705   0.852632  0.035915   0.277941  0.233740
19   5.00    0.033852    0.033829   0.844989  0.036182   0.274448  0.232622
20   5.25    0.033971    0.033959   0.837335  0.036563   0.271809  0.238613
21   5.50    0.034089    0.034089   0.829697  0.036825   0.269797  0.243270
22   5.75    0.034208    0.034219   0.822074  0.037089   0.268021  0.243416
23   6.00    0.034326    0.034350   0.814468  0.037356   0.266091  0.237775
24   6.25    0.034456    0.034494   0.806815  0.037942   0.263716  0.227010
25   6.50    0.034586    0.034638   0.799176  0.038237   0.261010  0.216967
26   6.75    0.034717    0.034782   0.791550  0.038533   0.258187  0.210060
27   7.00    0.034847    0.034926   0.783940  0.038832   0.255462  0.206982
28   7.25    0.034979    0.035073   0.776333  0.039194   0.253004  0.207593
29   7.50    0.035111    0.035221   0.768741  0.039501   0.250807  0.208720
30   7.75    0.035243    0.035369   0.761166  0.039810   0.248823  0.209430
31   8.00    0.035374    0.035517   0.753607  0.040121   0.247002  0.209561
32   8.25    0.035501    0.035659   0.746107  0.040210   0.245296  0.208884
33   8.50    0.035627    0.035802   0.738626  0.040511   0.243669  0.207743
34   8.75    0.035753    0.035945   0.731166  0.040814   0.242087  0.205962
35   9.00    0.035879    0.036089   0.723726  0.041120   0.240518  0.203424
36   9.25    0.036001    0.036228   0.716340  0.041244   0.238927  0.199919
37   9.50    0.036123    0.036368   0.708976  0.041544   0.237281  0.195520
38   9.75    0.036245    0.036508   0.701636  0.041846   0.235546  0.190017
39  10.00    0.036367    0.036649   0.694319  0.042150   0.233688  0.183291

## The Swaption

Consider the following swaption with the following features:
* underlying is a fixed-for-floating (SOFR) swap
* the underlying swap has **quarterly** payment frequency
* this is a **payer** swaption, which gives the holder the option to **pay** the fixed swap rate and receive SOFR.

### 1.1
Calculate the (relevant) forward swap rate. That is, the one-year forward 4-year swap rate.

### 1.2
Price the swaptions at the quoted implied volatilites and corresponding strikes, all using the just-calculated forward swap rate as the underlying.


### 1.3
To consider how the expiration and tenor matter, calculate the prices of a few other swaptions for comparison. 
* No need to get other implied vol quotes--just use the ATM implied vol you have for the swaption above. (Here we are just interested in how Black's formula changes with changes in tenor and expiration.)
* No need to calculate for all the strikes--just do the ATM strike.

Alternate swaptions
* The 3mo x 4yr swaption
* The 2yr x 4yr swaption
* the 1yr x 2yr swaption

Report these values and compare them to the price of the `1y x 4y` swaption.